
import React, { useRef, useState } from 'react';
import ReactMarkdown from 'https://esm.sh/react-markdown';

interface Props {
  result: string;
  startupName: string;
}

const ValuationResult: React.FC<Props> = ({ result, startupName }) => {
  const reportRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [copyStatus, setCopyStatus] = useState<string | null>(null);

  const handleExportPDF = async () => {
    const element = reportRef.current;
    if (!element) return;

    setIsExporting(true);

    const opt = {
      margin:       10,
      filename:     `${startupName.replace(/\s+/g, '_')}_Valuation_Report.pdf`,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { 
        scale: 2, 
        useCORS: true,
        letterRendering: true
      },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    try {
      // @ts-ignore - html2pdf is loaded via global script in index.html
      await html2pdf().set(opt).from(element).save();
    } catch (error) {
      console.error("PDF Export failed:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  const handleShare = async () => {
    // Extract valuation range from markdown (it's between the first set of double asterisks after "Estimated Valuation Range")
    const rangeMatch = result.match(/\*\*([^*]+)\*\*/);
    const range = rangeMatch ? rangeMatch[1] : 'Determined by Analyst';
    
    const shareTitle = `Valuation Report: ${startupName}`;
    const shareText = `Check out the VC Valuation Report for ${startupName}.\nEstimated Range: ${range}\n\nFull Appraisal:\n${result}\n\nGenerated by VC Valuation Analyst (SGI Consultants)`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: shareTitle,
          text: shareText,
          url: window.location.href
        });
      } catch (err) {
        console.debug('Share cancelled or failed', err);
        copyToClipboard(shareText);
      }
    } else {
      copyToClipboard(shareText);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopyStatus('Copied to clipboard!');
      setTimeout(() => setCopyStatus(null), 3000);
    }).catch(err => {
      console.error('Could not copy text: ', err);
      alert('Failed to copy to clipboard.');
    });
  };

  return (
    <div className="mt-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div 
        ref={reportRef} 
        className="bg-white p-8 rounded-xl shadow-xl border border-indigo-100"
      >
        <div className="flex justify-between items-start mb-6 border-b border-slate-100 pb-4">
          <div>
            <h2 className="text-2xl font-bold text-slate-800">Valuation Appraisal: {startupName}</h2>
            <p className="text-sm text-slate-500">Prepared by AI Senior Analyst • {new Date().toLocaleDateString('en-GB')}</p>
          </div>
          <div className="bg-indigo-50 text-indigo-700 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
            Confidential
          </div>
        </div>
        
        <div className="prose prose-slate max-w-none prose-headings:text-indigo-900 prose-strong:text-indigo-700 prose-ul:list-disc">
          <ReactMarkdown>{result}</ReactMarkdown>
        </div>
      </div>

      <div className="mt-8 flex flex-col items-center gap-4">
        <div className="flex flex-wrap justify-center gap-4">
          <button 
            onClick={handleExportPDF}
            disabled={isExporting}
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2 px-6 rounded-lg shadow-md transition-all flex items-center gap-2 disabled:opacity-50"
          >
            {isExporting ? (
              <i className="fas fa-circle-notch animate-spin"></i>
            ) : (
              <i className="fas fa-file-pdf"></i>
            )}
            {isExporting ? "Generating PDF..." : "Download PDF Report"}
          </button>

          <button 
            onClick={handleShare}
            className="bg-emerald-600 hover:bg-emerald-700 text-white font-medium py-2 px-6 rounded-lg shadow-md transition-all flex items-center gap-2"
          >
            <i className="fas fa-share-alt"></i>
            Share Report
          </button>
          
          <button 
            onClick={() => window.print()}
            className="bg-white border border-slate-300 text-slate-600 hover:bg-slate-50 font-medium py-2 px-6 rounded-lg transition-all flex items-center gap-2"
          >
            <i className="fas fa-print"></i>
            Standard Print
          </button>
        </div>
        
        {copyStatus && (
          <div className="text-emerald-600 text-sm font-medium animate-bounce">
            <i className="fas fa-check-circle mr-1"></i> {copyStatus}
          </div>
        )}
      </div>
    </div>
  );
};

export default ValuationResult;
