
import React, { useRef, useState } from 'react';
import ReactMarkdown from 'https://esm.sh/react-markdown';

interface Props {
  result: string;
  startupName: string;
}

const ValuationResult: React.FC<Props> = ({ result, startupName }) => {
  const reportRef = useRef<HTMLDivElement>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [copyStatus, setCopyStatus] = useState<string | null>(null);

  const handleExportPDF = async () => {
    const element = reportRef.current;
    if (!element) return;

    setIsExporting(true);

    const opt = {
      margin:       10,
      filename:     `${startupName.replace(/\s+/g, '_')}_Valuation_Report.pdf`,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { 
        scale: 2, 
        useCORS: true,
        letterRendering: true
      },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    try {
      // @ts-ignore - html2pdf is loaded via global script in index.html
      await html2pdf().set(opt).from(element).save();
    } catch (error) {
      console.error("PDF Export failed:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  const handleShare = async () => {
    const rangeMatch = result.match(/\*\*([^*]+)\*\*/);
    const range = rangeMatch ? rangeMatch[1] : 'Determined by Analyst';
    
    const shareTitle = `Valuation Report: ${startupName}`;
    const shareText = `Check out the SGI Startup Valuation Report for ${startupName}.\nEstimated Range: ${range}\n\nFull Appraisal:\n${result}\n\nGenerated by SGI Startup Valuation Tool`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: shareTitle,
          text: shareText,
          url: window.location.href
        });
      } catch (err) {
        console.debug('Share cancelled or failed', err);
        copyToClipboard(shareText);
      }
    } else {
      copyToClipboard(shareText);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopyStatus('Copied to clipboard!');
      setTimeout(() => setCopyStatus(null), 3000);
    }).catch(err => {
      console.error('Could not copy text: ', err);
      alert('Failed to copy to clipboard.');
    });
  };

  return (
    <div className="mt-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div 
        ref={reportRef} 
        className="bg-white p-8 md:p-12 rounded-xl shadow-xl border border-slate-200"
      >
        <div className="flex justify-between items-start mb-10 border-b border-slate-100 pb-6">
          <div>
            <h2 className="text-3xl font-bold text-slate-900 mb-1">Valuation Appraisal: {startupName}</h2>
            <p className="text-slate-500 font-medium">Prepared by Senior VC Analyst • {new Date().toLocaleDateString('en-GB')}</p>
          </div>
          <div className="bg-slate-100 text-slate-600 px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-widest border border-slate-200">
            Internal / Confidential
          </div>
        </div>
        
        <div className="prose prose-slate max-w-none 
          prose-headings:text-slate-900 prose-headings:font-bold 
          prose-h2:text-2xl prose-h2:mt-12 prose-h2:mb-6 prose-h2:pb-3 prose-h2:border-b prose-h2:border-slate-100
          prose-h3:text-xl prose-h3:mt-10 prose-h3:mb-4 prose-h3:text-indigo-900
          prose-p:text-slate-600 prose-p:leading-relaxed prose-p:mb-6
          prose-strong:text-slate-900 prose-strong:font-bold
          prose-ul:my-6 prose-li:my-2 prose-li:text-slate-600
          prose-hr:my-12 prose-hr:border-slate-200">
          <ReactMarkdown>{result}</ReactMarkdown>
        </div>
      </div>

      <div className="mt-8 flex flex-col items-center gap-4 print:hidden">
        <div className="flex flex-wrap justify-center gap-4">
          <button 
            onClick={handleExportPDF}
            disabled={isExporting}
            className="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2.5 px-8 rounded-lg shadow-md transition-all flex items-center gap-2 disabled:opacity-50"
          >
            {isExporting ? (
              <i className="fas fa-circle-notch animate-spin"></i>
            ) : (
              <i className="fas fa-file-pdf"></i>
            )}
            {isExporting ? "Generating PDF..." : "Download PDF Report"}
          </button>

          <button 
            onClick={handleShare}
            className="bg-emerald-600 hover:bg-emerald-700 text-white font-semibold py-2.5 px-8 rounded-lg shadow-md transition-all flex items-center gap-2"
          >
            <i className="fas fa-share-alt"></i>
            Share Report
          </button>
          
          <button 
            onClick={() => window.print()}
            className="bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 font-semibold py-2.5 px-8 rounded-lg transition-all flex items-center gap-2 shadow-sm"
          >
            <i className="fas fa-print"></i>
            Print
          </button>
        </div>
        
        {copyStatus && (
          <div className="text-emerald-600 text-sm font-semibold animate-pulse">
            <i className="fas fa-check-circle mr-1"></i> {copyStatus}
          </div>
        )}
      </div>
    </div>
  );
};

export default ValuationResult;
